# fly.toml app configuration file generated for bun-personal-site on 2023-10-22T20:36:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bun-personal-site"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
